CREATE OR REPLACE PROCEDURE SP_CREATE_COMMENT (
    P_USER_ID IN COMMENTS.USER_ID%TYPE,
    P_POST_ID IN COMMENTS.POST_ID%TYPE,
    P_CONTENT IN COMMENTS.CONTENT%TYPE,
    P_COMMENT_ID OUT COMMENTS.COMMENT_ID%TYPE,
    P_RESULT OUT NUMBER
)
AS
    V_POST_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_POST_COUNT
    FROM POSTS
    WHERE POST_ID = P_POST_ID;

    IF V_POST_COUNT = 0 THEN
        P_COMMENT_ID := NULL;
        P_RESULT := 0;
        RETURN;
    END IF;

    INSERT INTO COMMENTS (
        USER_ID,
        POST_ID,
        CONTENT,
        CREATED_AT
    )
    VALUES (
        P_USER_ID,
        P_POST_ID,
        P_CONTENT,
        CURRENT_TIMESTAMP
    )
    RETURNING COMMENT_ID INTO P_COMMENT_ID;

    P_RESULT := 1;

EXCEPTION
    WHEN OTHERS THEN
        P_COMMENT_ID := NULL;
        P_RESULT := -1;
        RAISE;
END SP_CREATE_COMMENT;
/