CREATE OR REPLACE PROCEDURE SP_CREATE_POST (
    P_USER_ID IN POSTS.USER_ID%TYPE,
    P_CONTENT IN POSTS.CONTENT%TYPE,
    P_IMAGE IN POSTS.IMAGE%TYPE,

    P_POST_ID OUT POSTS.POST_ID%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN
    INSERT INTO POSTS (
        USER_ID,
        CONTENT,
        IMAGE,
        CREATED_AT,
        UPDATED_AT
    )
    VALUES (
        P_USER_ID,
        P_CONTENT,
        P_IMAGE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
    RETURNING POST_ID INTO P_POST_ID;

    P_RESULT := 1;

EXCEPTION
    WHEN OTHERS THEN
        P_POST_ID := NULL;
        P_RESULT := -1;
        RAISE;
END SP_CREATE_POST;
/