CREATE OR REPLACE PROCEDURE SP_DELETE_POST (
    P_POST_ID IN POSTS.POST_ID%TYPE,
    P_USER_ID IN POSTS.USER_ID%TYPE,
    P_RESULT OUT NUMBER
)
AS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM POSTS
    WHERE POST_ID = P_POST_ID
      AND USER_ID = P_USER_ID;

    IF V_COUNT = 0 THEN
        P_RESULT := 0;
        RETURN;
    END IF;

    DELETE FROM COMMENTS
    WHERE POST_ID = P_POST_ID;

    DELETE FROM POSTS
    WHERE POST_ID = P_POST_ID
      AND USER_ID = P_USER_ID;

    P_RESULT := 1;

EXCEPTION
    WHEN OTHERS THEN
        P_RESULT := -1;
        RAISE;
END SP_DELETE_POST;
/