CREATE OR REPLACE PROCEDURE SP_UPDATE_POST (
    P_POST_ID IN POSTS.POST_ID%TYPE,
    P_USER_ID IN POSTS.USER_ID%TYPE,
    P_CONTENT IN POSTS.CONTENT%TYPE,
    P_IMAGE IN POSTS.IMAGE%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN
    UPDATE POSTS
    SET
        CONTENT = P_CONTENT,
        IMAGE = P_IMAGE,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE POST_ID = P_POST_ID
      AND USER_ID = P_USER_ID;

    IF SQL%ROWCOUNT = 0 THEN
        P_RESULT := 0;
    ELSE
        P_RESULT := 1;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        P_RESULT := -1;
        RAISE;
END SP_UPDATE_POST;
/