CREATE OR REPLACE PROCEDURE SP_LOGIN (
    P_PHONE IN USERS.PHONE%TYPE,
    P_USER_ID OUT USERS.USER_ID%TYPE,
    P_PASSWORD_HASH OUT USERS.PASSWORD_HASH%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN
    SELECT USER_ID, PASSWORD_HASH
    INTO P_USER_ID, P_PASSWORD_HASH
    FROM USERS
    WHERE PHONE = P_PHONE;


    P_RESULT := 1;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_USER_ID := NULL;
        P_PASSWORD_HASH := NULL;
        P_RESULT := 0;

    WHEN OTHERS THEN
        P_USER_ID := NULL;
        P_PASSWORD_HASH := NULL;
        P_RESULT := -1;
        RAISE;
END SP_LOGIN;
/