CREATE OR REPLACE PROCEDURE SP_CONSUME_OTP (
    P_VERIFICATION_ID IN VERIFICATION_CODES.VERIFICATION_ID%TYPE,
    P_USER_ID IN VERIFICATION_CODES.USER_ID%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN

    UPDATE VERIFICATION_CODES
    SET USED_AT = CURRENT_TIMESTAMP
    WHERE VERIFICATION_ID = P_VERIFICATION_ID
        AND USER_ID = P_USER_ID
        AND USED_AT IS NULL
        AND EXPIRES_AT > CURRENT_TIMESTAMP;

    IF SQL%ROWCOUNT = 0 THEN
        P_RESULT := 0;
        RETURN;
    END IF;

    UPDATE USERS
    SET PHONE_VERIFIED = 1,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE USER_ID = P_USER_ID;

    P_RESULT := 1;

EXCEPTION
    WHEN OTHERS THEN
        P_RESULT := -1;
        RAISE;
END SP_CONSUME_OTP;
/