CREATE OR REPLACE PROCEDURE SP_CREATE_OTP (
    P_USER_ID IN VERIFICATION_CODES.USER_ID%TYPE,
    P_PURPOSE IN VERIFICATION_CODES.PURPOSE%TYPE,
    P_CODE_HASH IN VERIFICATION_CODES.CODE_HASH%TYPE,
    P_EXPIRES_AT IN VERIFICATION_CODES.EXPIRES_AT%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN
    INSERT INTO VERIFICATION_CODES (
        USER_ID,
        PURPOSE,
        CODE_HASH,
        EXPIRES_AT
    )
    VALUES (
        P_USER_ID,
        P_PURPOSE,
        P_CODE_HASH,
        P_EXPIRES_AT
    );

    P_RESULT := 1;

EXCEPTION
    WHEN OTHERS THEN
        P_RESULT := -1;
        RAISE;
END SP_CREATE_OTP;
/