CREATE OR REPLACE PROCEDURE SP_GET_ACTIVE_OTP (
    P_USER_ID IN VERIFICATION_CODES.USER_ID%TYPE,
    P_PURPOSE IN VERIFICATION_CODES.PURPOSE%TYPE,
    P_VERIFICATION_ID OUT VERIFICATION_CODES.VERIFICATION_ID%TYPE,
    P_CODE_HASH OUT VERIFICATION_CODES.CODE_HASH%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN
    SELECT VERIFICATION_ID, CODE_HASH
    INTO P_VERIFICATION_ID, P_CODE_HASH
    FROM VERIFICATION_CODES
    WHERE USER_ID = P_USER_ID
      AND PURPOSE = P_PURPOSE
      AND USED_AT IS NULL
      AND EXPIRES_AT > CURRENT_TIMESTAMP
    ORDER BY CREATED_AT DESC
    FETCH FIRST 1 ROW ONLY;

    P_RESULT := 1; -- OTP verification successful

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_VERIFICATION_ID := NULL;
        P_CODE_HASH := NULL;
        P_RESULT := 0;

    WHEN OTHERS THEN
        P_VERIFICATION_ID := NULL;
        P_CODE_HASH := NULL;
        P_RESULT := -1;
        RAISE;
END SP_GET_ACTIVE_OTP;
/