CREATE OR REPLACE PROCEDURE SP_GET_USER_PROFILE (
    P_USER_ID IN USERS.USER_ID%TYPE,
    P_USER_NAME OUT USERS.USER_NAME%TYPE,
    P_PHONE OUT USERS.PHONE%TYPE,
    P_EMAIL OUT USERS.EMAIL%TYPE,
    P_PHONE_VERIFIED OUT USERS.PHONE_VERIFIED%TYPE,
    P_EMAIL_VERIFIED OUT USERS.EMAIL_VERIFIED%TYPE,
    P_COVER_IMAGE OUT USERS.COVER_IMAGE%TYPE,
    P_BIOGRAPHY OUT USERS.BIOGRAPHY%TYPE,
    P_RESULT OUT NUMBER
)
AS
BEGIN
    SELECT
        USER_NAME,
        PHONE,
        EMAIL,
        PHONE_VERIFIED,
        EMAIL_VERIFIED,
        COVER_IMAGE,
        BIOGRAPHY
    INTO
        P_USER_NAME,
        P_PHONE,
        P_EMAIL,
        P_PHONE_VERIFIED,
        P_EMAIL_VERIFIED,
        P_COVER_IMAGE,
        P_BIOGRAPHY
    FROM USERS
    WHERE USER_ID = P_USER_ID;

    P_RESULT := 1;


EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_USER_NAME := NULL;
        P_PHONE := NULL;
        P_EMAIL := NULL;
        P_PHONE_VERIFIED := NULL;
        P_EMAIL_VERIFIED := NULL;
        P_COVER_IMAGE := NULL;
        P_BIOGRAPHY := NULL;
        P_RESULT := 0;

    WHEN OTHERS THEN
        P_RESULT := -1;
        RAISE;
END SP_GET_USER_PROFILE;
/